name: Create item in GitHub Project

on:
  issues: 
    types: [ opened, reopened ]
  push:

jobs:
  create-item:
    runs-on: ubuntu-latest
    steps:

      - name: Get project data
        env:
          ORGANIZATION: '${{ github.repository_owner }}'
          PROJECT_NUMBER: '1'
          NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}
        run: |
          my_org="dvalleorg"
          my_num=1
          gh api graphql -f query='
            query($organization: String! $number: Int!){
              organization(login: $organization){
                projectV2(number: $number) {
                  id
                }
              }
            }' -f organization=$my_org -F number=$my_num
